"""Replication setup and cluster management for PostgreSQL worktrees."""

import logging
import os
import re
import subprocess
from pathlib import Path
from typing import Optional

from lib.config import PGSQL_DIR, STANDBY_PORT_STRIDE
from lib.operations import make_run_wrapper

logger = logging.getLogger("pg_replication")
_run = make_run_wrapper(logger)


def standby_port(primary_port: int, standby_index: int) -> int:
    """Derive standby port from primary port and index."""
    return primary_port + standby_index * STANDBY_PORT_STRIDE


def standby_data_dir(project_dir: Path, standby_index: int) -> Path:
    """Get data directory path for a standby."""
    return project_dir / f"data-s{standby_index}"


def configure_primary(project_dir: Path, port: int, standbys: list):
    """Configure primary for replication and restart.

    Args:
        project_dir: The project install directory (e.g., ~/pgsql/feature-x)
        port: Primary port number
        standbys: List of dicts with 'type' key (streaming_sync, streaming_async, logical)
    """
    data_dir = project_dir / "data"
    pg_ctl = project_dir / "bin" / "pg_ctl"

    # Determine wal_level
    has_logical = any(s["type"] == "logical" for s in standbys)
    wal_level = "logical" if has_logical else "replica"

    # Determine synchronous_standby_names
    sync_names = []
    for i, sb in enumerate(standbys, 1):
        if sb["type"] == "streaming_sync":
            sync_names.append(f"s{i}")

    # Append to postgresql.conf
    conf = data_dir / "postgresql.conf"
    repl_conf = [
        "",
        "# Replication settings (auto-generated by pg_init)",
        f"wal_level = {wal_level}",
        "max_wal_senders = 10",
        "hot_standby = on",
    ]
    if sync_names:
        names_str = ", ".join(sync_names)
        repl_conf.append(
            f"synchronous_standby_names = 'FIRST {len(sync_names)} ({names_str})'"
        )

    with open(str(conf), "a") as f:
        f.write("\n".join(repl_conf) + "\n")

    # Append to pg_hba.conf
    hba = data_dir / "pg_hba.conf"
    hba_entries = [
        "",
        "# Replication connections (auto-generated by pg_init)",
        "local   replication     all                                     trust",
        "host    replication     all             127.0.0.1/32            trust",
    ]
    with open(str(hba), "a") as f:
        f.write("\n".join(hba_entries) + "\n")

    # Restart primary to apply settings
    logger.info("Restarting primary to apply replication settings...")
    subprocess.run(
        [str(pg_ctl), "-D", str(data_dir), "restart", "-w"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, text=True,
    )


def create_standby(project_dir: Path, primary_port: int,
                    standby_index: int, repl_type: str):
    """Create a standby instance using pg_basebackup or initdb.

    Args:
        project_dir: The project install directory
        primary_port: Primary port number
        standby_index: 1-based standby index
        repl_type: 'streaming_sync', 'streaming_async', or 'logical'
    """
    sb_port = standby_port(primary_port, standby_index)
    data_dir = standby_data_dir(project_dir, standby_index)
    pg_basebackup = project_dir / "bin" / "pg_basebackup"
    initdb = project_dir / "bin" / "initdb"
    pg_ctl = project_dir / "bin" / "pg_ctl"
    psql = project_dir / "bin" / "psql"

    if repl_type in ("streaming_sync", "streaming_async"):
        _create_streaming_standby(
            project_dir, data_dir, pg_basebackup, pg_ctl,
            primary_port, sb_port, standby_index, repl_type,
        )
    elif repl_type == "logical":
        _create_logical_standby(
            project_dir, data_dir, initdb, pg_ctl, psql,
            primary_port, sb_port, standby_index,
        )
    else:
        raise ValueError(f"Unknown replication type: {repl_type}")


def _create_streaming_standby(project_dir, data_dir, pg_basebackup, pg_ctl,
                               primary_port, sb_port, standby_index, repl_type):
    """Create a streaming replication standby via pg_basebackup."""
    logger.info(f"Creating streaming standby S{standby_index} "
                f"(port {sb_port}, {repl_type})...")

    # pg_basebackup -R creates standby.signal and sets primary_conninfo
    _run([
        str(pg_basebackup),
        "-h", "localhost",
        "-p", str(primary_port),
        "-D", str(data_dir),
        "-R", "-X", "stream", "-c", "fast",
    ])

    # Edit postgresql.conf for standby
    conf = data_dir / "postgresql.conf"
    standby_conf = [
        "",
        f"# Standby S{standby_index} settings (auto-generated)",
        f"port = {sb_port}",
        "logging_collector = on",
        "hot_standby = on",
    ]
    with open(str(conf), "a") as f:
        f.write("\n".join(standby_conf) + "\n")

    # For sync streaming, add application_name to primary_conninfo
    if repl_type == "streaming_sync":
        auto_conf = data_dir / "postgresql.auto.conf"
        content = auto_conf.read_text()
        app_name = f"s{standby_index}"
        # Find the closing quote of primary_conninfo value and insert before it.
        # The value may contain '' (escaped quotes), so we parse character by character.
        lines = content.splitlines(True)
        new_lines = []
        for line in lines:
            stripped = line.lstrip()
            if stripped.startswith("primary_conninfo"):
                # Find last single quote (closing quote of the value)
                last_q = line.rfind("'")
                if last_q > 0:
                    line = line[:last_q] + f" application_name={app_name}" + line[last_q:]
            new_lines.append(line)
        auto_conf.write_text("".join(new_lines))

    # Start standby
    logger.info(f"Starting standby S{standby_index} on port {sb_port}...")
    result = subprocess.run(
        [str(pg_ctl), "-D", str(data_dir), "-o", f"-p {sb_port}", "start"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Failed to start standby S{standby_index} (exit {result.returncode})"
        )
    logger.info(f"Standby S{standby_index} started.")


def _create_logical_standby(project_dir, data_dir, initdb, pg_ctl, psql,
                             primary_port, sb_port, standby_index):
    """Create a logical replication standby via initdb + CREATE SUBSCRIPTION."""
    logger.info(f"Creating logical standby S{standby_index} "
                f"(port {sb_port})...")

    # Create publication on primary (if not already exists)
    _run([
        str(psql), "-h", "localhost", "-p", str(primary_port), "postgres",
        "-c", "DO $$ BEGIN "
              "IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'pub_all') THEN "
              "CREATE PUBLICATION pub_all FOR ALL TABLES; "
              "END IF; END $$;",
    ])

    # initdb for the logical subscriber
    _run([str(initdb), "--encoding=utf8", "--no-locale", "-D", str(data_dir)])

    # Configure subscriber postgresql.conf
    conf = data_dir / "postgresql.conf"
    logical_conf = [
        "",
        f"# Logical standby S{standby_index} settings (auto-generated)",
        f"port = {sb_port}",
        "logging_collector = on",
        "wal_level = logical",
    ]
    with open(str(conf), "a") as f:
        f.write("\n".join(logical_conf) + "\n")

    # Start subscriber
    logger.info(f"Starting logical standby S{standby_index} on port {sb_port}...")
    result = subprocess.run(
        [str(pg_ctl), "-D", str(data_dir), "-o", f"-p {sb_port}", "start"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Failed to start logical standby S{standby_index} (exit {result.returncode})"
        )

    # Create subscription
    _run([
        str(psql), "-h", "localhost", "-p", str(sb_port), "postgres",
        "-c", f"CREATE SUBSCRIPTION sub_s{standby_index} "
              f"CONNECTION 'host=localhost port={primary_port} dbname=postgres' "
              f"PUBLICATION pub_all;",
    ])
    logger.info(f"Logical standby S{standby_index} started with subscription.")


# ---------------------------------------------------------------------------
# Cluster operations
# ---------------------------------------------------------------------------

def _pg_ctl_action(project_dir: Path, data_dir: Path, port: int,
                   action: str, label: str):
    """Run pg_ctl action (start/stop/restart/reload) on one instance."""
    pg_ctl = project_dir / "bin" / "pg_ctl"
    if not pg_ctl.exists():
        logger.warning(f"pg_ctl not found for {label}, skipping")
        return
    if not data_dir.exists():
        logger.warning(f"Data dir {data_dir} not found for {label}, skipping")
        return

    cmd = [str(pg_ctl), "-D", str(data_dir)]
    if action == "start":
        cmd.extend(["-o", f"-p {port}", "start"])
    elif action == "stop":
        cmd.extend(["stop", "-m", "fast"])
    elif action == "restart":
        cmd.extend(["-o", f"-p {port}", "restart"])
    elif action == "reload":
        cmd.append("reload")
    else:
        raise ValueError(f"Unknown action: {action}")

    logger.info(f"{action.capitalize()} {label} (port {port})...")
    result = subprocess.run(
        cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, text=True,
        timeout=30,
    )
    if result.returncode != 0 and action != "stop":
        raise RuntimeError(f"pg_ctl {action} failed for {label} (exit {result.returncode})")


def stop_cluster(project_dir: Path, name: str, port: int,
                 standbys: list):
    """Stop all instances in a cluster (standbys first, then primary)."""
    # Stop standbys in reverse order
    for sb in reversed(standbys):
        idx = sb["standby_index"]
        sb_data = standby_data_dir(project_dir, idx)
        sb_p = standby_port(port, idx)
        _pg_ctl_action(project_dir, sb_data, sb_p, "stop", f"standby S{idx}")

    # Stop primary
    primary_data = project_dir / "data"
    _pg_ctl_action(project_dir, primary_data, port, "stop", "primary")


def start_cluster(project_dir: Path, name: str, port: int,
                  standbys: list):
    """Start all instances in a cluster (primary first, then standbys)."""
    # Start primary
    primary_data = project_dir / "data"
    _pg_ctl_action(project_dir, primary_data, port, "start", "primary")

    # Start standbys in order
    for sb in standbys:
        idx = sb["standby_index"]
        sb_data = standby_data_dir(project_dir, idx)
        sb_p = standby_port(port, idx)
        _pg_ctl_action(project_dir, sb_data, sb_p, "start", f"standby S{idx}")


def restart_cluster(project_dir: Path, name: str, port: int,
                    standbys: list):
    """Restart all instances (stop all, then start all)."""
    stop_cluster(project_dir, name, port, standbys)
    start_cluster(project_dir, name, port, standbys)


def reload_cluster(project_dir: Path, name: str, port: int,
                   standbys: list):
    """Reload configuration for all instances."""
    primary_data = project_dir / "data"
    _pg_ctl_action(project_dir, primary_data, port, "reload", "primary")

    for sb in standbys:
        idx = sb["standby_index"]
        sb_data = standby_data_dir(project_dir, idx)
        sb_p = standby_port(port, idx)
        _pg_ctl_action(project_dir, sb_data, sb_p, "reload", f"standby S{idx}")


def build_cluster(src_dir: Path, project_dir: Path, port: int,
                  standbys: list):
    """Rebuild from source, reinstall, and restart all instances."""
    nproc = os.cpu_count() or 1

    logger.info(f"Building PostgreSQL (make -j{nproc})...")
    _run(["make", "-s", "world", f"-j{nproc}"], cwd=str(src_dir))

    logger.info("Installing PostgreSQL...")
    _run(["make", "-s", "install-world"], cwd=str(src_dir))

    restart_cluster(project_dir, project_dir.name, port, standbys)
